development:
  adapter: postgresql
  encoding: unicode
  database: zackdragoon_development
  pool: 5
#  username: rennan
#  password:

test:
  adapter: postgresql
  encoding: unicode
  database: zackdragoon_test
  pool: 5
#  username: rennan
#  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_production
  pool: 5
  username: rennan
  password:
